### REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "name": "Fajar M. Hamka",
   "email": "fajarmh@gmail.com",
   "password": "123456",
   "confPassword": "123456"
}

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
   "email": "fajarmh@gmail.com",
   "password": "123456"
}

### Get Users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJGYWphciBNLiBIYW1rYSIsImVtYWlsIjoiZmFqYXJtaEBnbWFpbC5jb20iLCJpYXQiOjE2NTAxOTY4MTIsImV4cCI6MTY1MDE5Njg0Mn0.exuTx9ry2INXl1gWZ9nkPaFjui8zGU9-9KjAn2w5Rv0

### GET TOKEN
GET http://localhost:5000/token

### LOGOUT
DELETE http://localhost:5000/auth/logout