### REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
   "name": "Fajar M. Hamka",
   "email": "fajarmh@gmail.com",
   "password": "123456",
   "confPassword": "123456"
}

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
   "email": "fajarmh@gmail.com",
   "password": "123456"
}

### Get Users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJGYWphciBNLiBIYW1rYSIsImVtYWlsIjoiZmFqYXJtaEBnbWFpbC5jb20iLCJpYXQiOjE2NTAzNzAwMDUsImV4cCI6MTY1MDM3MDAzNX0.V29huvGEppxwa8gRFfcHx6Icd6VyBJx6C_Gqo0Gc3pk

### Get Users Info
GET http://localhost:5000/users

### GET TOKEN
GET http://localhost:5000/token

### LOGOUT
DELETE http://localhost:5000/auth/logout


### ADD CART
POST http://localhost:5000/carts/add
Content-Type: application/json

{
   "plastic": 2,
   "skincare": 4,
   "kaca": 5
}

### UPDATE <pake id>
PUT http://localhost:5000/carts/solved/8

### GET DATA USERS CARTS
GET http://localhost:5000/carts